spring.application.name=apexium.log

# Salesforce Configuration
# Use environment variables for sensitive data to keep the repository public-safe
salesforce.login-url=${SALESFORCE_INSTANCE_ORG:}
salesforce.client-id=${SALESFORCE_CLIENT_ID:}
salesforce.client-secret=${SALESFORCE_CLIENT_SECRET:}
salesforce.grant-type=${SALESFORCE_GRANT_TYPE:}
salesforce.api-version=${SALESFORCE_API_VERSION:}

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sfdc_logs}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# spring.data.redis.password=
spring.cache.type=redis
# Cache TTL configurations (custom property we might use in config class)
cache.ttl.token=3600
cache.ttl.metadata=3600

# Polling service
# six hour: metadata polling service
metadata.poll.rate=PT6H
metadata.poll.batch-size=200
# a minute: log polling service
log.poll.rate=PT1M

# Log Retention Configuration
log.retention.days=15
log.retention.cron=0 0 6 * * ?

# MinIO Configuration
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=${MINIO_BUCKET_NAME:sfdc-bucket}

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.metrics.enable.jvm=true

